# deploys the starbug continers with transport layer security
#
# Assumes containers are built and pulled to the local repo
#
# one time setup
#
# docker volume create --name=letsencrypt
# docker volume create --name=starbugbackup
# docker volume create -—name=starbugconfig
# docker volume create -—name=starbugdata
# docker volume create -—name=starbuglogs
# docker volume create -—name=webroot
# docker volume create -—name=wellknown
#
# manage containers
#
# docker-compose -f tls.starbug.com-compose.yaml up -d
# docker-compose -f tls.starbug.com-compose.yaml ps
# docker-compose -f tls.starbug.com-compose.yaml down

version: '3'

networks:
  starbugnet:

services:

  aai:
    image: aai.starbug.com
    container_name: aai.starbug.com_00
    environment:
      AAI_FLASK_CONFIG: /opt/starbug.com/config/aai-flask-deployment-config.py
    restart: always
    networks:
      - starbugnet
    ports:
      - "8080:8080"
    volumes:
      - starbugconfig:/opt/starbug.com/config
      - starbuglogs:/opt/starbug.com/logs


  starbugdb:
    image: starbugdb
    container_name: starbugdb_00
    restart: always
    networks:
      - starbugnet
    ports:
      - "27017:27017"
    volumes:
      - starbugbackup:/opt/starbug.com/backup
      - starbugdata:/data/db
      - starbuglogs:/opt/starbug.com/logs


  obsui:
    image: obsui
    container_name: obsui_00
    environment:
      OBSUI_FLASK_CONFIG: /opt/starbug.com/config/obsui_starbug.cfg
    depends_on:
      - aai
      - starbugdb
    restart: always
    networks:
      - starbugnet
    ports:
      - "8090:8090"
    volumes:
      - starbugconfig:/opt/starbug.com/config
      - starbuglogs:/opt/starbug.com/logs


  tls.starbug.com:
    image: tls.starbug.com
    container_name: tls.starbug.com_00
    depends_on:
      - aai
      - starbugdb
      - obsui
    restart: always
    networks:
      - starbugnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - starbugbackup:/opt/starbug.com/backup
      - starbuglogs:/opt/starbug.com/logs
      - /var/run/docker.sock:/tmp/docker.sock
      - wellknown:/opt/starbug.com/www/.well-known


# persistent storage
volumes:
  letsencrypt:
     external: true
  starbugbackup:
    external: true
  starbugconfig:
    external: true
  starbugdata:
    external: true
  starbuglogs:
    external: true
  webroot:
    external: true
  wellknown:
    external: true
